"""An offline review gallery of actual Blender renders, never concept mockups."""
from pathlib import Path
import re,html
root=Path(__file__).resolve().parents[1]
rows=re.findall(r'^    (\d+)\|([^|]+)\|', (root/'CloudChess/CollectionCatalog.swift').read_text(),re.M)
parts=[]
for raw,name in rows:
 id=int(raw);rarity='Legendary' if id>120 else 'Rare' if id>100 else 'Common'
 parts.append(f'<article class="{rarity.lower()}"><header><h2>{html.escape(name)}</h2><span>{rarity}</span></header><a href="{id}-board.png"><img src="{id}-board.png" alt="{html.escape(name)}: both armies and matching board" loading="lazy"></a><details><summary>Six-piece close-up</summary><img src="{id}-portrait.png" alt="Six-piece sculpted set" loading="lazy"></details><a class="source" href="{id}-atelier.blend">Blender source ↗</a></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CloudChess · Atelier</title><style>
*{box-sizing:border-box}body{margin:0;background:#121b24;color:#f0eee9;font:16px -apple-system,BlinkMacSystemFont,sans-serif;padding:4vw}main{max-width:1400px;margin:auto}h1{font-weight:400;font-size:clamp(32px,5vw,70px);letter-spacing:-.04em;margin:0}p{color:#a9b7c3;line-height:1.6}nav{display:flex;gap:12px;margin:28px 0;flex-wrap:wrap}button{border:1px solid #3d4c5b;background:#1d2935;color:inherit;border-radius:24px;padding:11px 22px;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#e9ddc3;color:#202b37}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{background:#1a2631;border:1px solid #364654;border-radius:20px;overflow:hidden}header{padding:22px;display:flex;justify-content:space-between;gap:10px;align-items:center}h2{font-size:19px;font-weight:500;margin:0}span{font-size:12px;color:#b8c8d6}.rare span{color:#c7aeed}.legendary span{color:#f2c991}img{display:block;width:100%;height:auto}details{padding:18px 22px}summary{cursor:pointer;color:#bfcbd4}details img{margin-top:18px}.source{display:block;padding:0 22px 20px;color:#b4c5d4;font-size:13px;text-decoration:none}article[hidden]{display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}header{padding:18px}body{padding:20px}}
</style><main><h1>CloudChess Atelier</h1><p>10 Common · 5 Rare · 2 Legendary<br>Actual modeled assets, photographed in Blender. Each set includes both armies and a matching board.</p><nav aria-label="Rarity"><button aria-pressed="true" data-filter="all">All 17</button><button aria-pressed="false" data-filter="common">Common</button><button aria-pressed="false" data-filter="rare">Rare</button><button aria-pressed="false" data-filter="legendary">Legendary</button></nav><div class="grid">'''+''.join(parts)+'''</div></main><script>document.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('article').forEach(a=>a.hidden=b.dataset.filter!=='all'&&!a.classList.contains(b.dataset.filter))})</script></html>'''
(root/'art/atelier/index.html').write_text(page)
print(f'{len(rows)} original collections in review gallery')
